# docker push mpilkou/djando_mysql_postgresql:latest

FROM python:3

RUN apt-get update \
    && apt-get install -y

RUN apt-get install -y python3-pip nano systemctl nginx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt ./requirements.txt

RUN python3 -m pip install -r requirements.txt

# VOLUME [ "/usr/src/app/django_code" ]
WORKDIR /usr/src/app/django_code

# RUN python3 manage.py startproject djngo_code
# ENTRYPOINT (cannot be overrited on container start) file bash to execute on run
# RUN python3 manage.py makemigrations \
#     && python3 manage.py manage.py migrate \
#     && python3 manage.py collectstatic

EXPOSE 8000 80

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
# CMD [ "/bin/bash" ]
# ENTRYPOINT ["bash"]