version: "3.9"
   
services:
  mysql:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE : mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_user
      MYSQL_ROOT_PASSWORD: root
    networks:
      mynet:
        ipv4_address: 10.10.2.20
    ports:
      - "3306:3306"
  postgres:
    image: postgres
    container_name: postgres_container
    volumes:
      - ./docker-volumes/psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=psql_db
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_user
    ports:
      - "5432:5432"
    networks:
      mynet:
        ipv4_address: 10.10.2.30
  web:
    build: .
    container_name: django_container
    depends_on:
      - mysql
      - postgres
    volumes:
      - type: bind
        source: ./docker-volumes/django_code
        target: /usr/src/app/django_code
    # entrypoint: django-admin startproject django_code
    ports:
      - "8000:8000"
      - "80:80"
    networks:
      mynet:
        ipv4_address: 10.10.2.10

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.2.0/24
         gateway: 10.10.2.1