# sudo docker-compose up
# sudo docker-compose down -v
# db connect localhost = postgress (service)

version: '3'

services:

  drupal:
    image: drupal
    ports:
      - "8080:80" # 8080 on host and send to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
 
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypasswd

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
